version: "3.8"

x-logging: &loki-logging
    driver: loki
    options:
      loki-url: "${DEPLOY_LOKI_URL}"
      loki-retries: 5
      loki-batch-size: 400

services:
  web:
    image: ${DEPLOY_IMAGE_WEB:-ghcr.io/open-webui/open-webui:main}
#:log |    logging: *loki-logging
#:env |    env_file: ${DEPLOY_ENV_WEB}
#:port|    ports:
#:port|      - ${DEPLOY_PORT_WEB:-8080}:8080
    environment:
#:offline|      - OFFLINE_MODE=${OFFLINE_MODE:-true}
#:offline|      - HF_HUB_OFFLINE=${HF_HUB_OFFLINE:-1}
#:offline|      - RAG_EMBEDDING_MODEL_AUTO_UPDATE=${RAG_EMBEDDING_MODEL_AUTO_UPDATE:-false}
#:offline|      - RAG_RERANKING_MODEL_AUTO_UPDATE=${RAG_RERANKING_MODEL_AUTO_UPDATE:-false}
#:offline|      - WHISPER_MODEL_AUTO_UPDATE=${WHISPER_MODEL_AUTO_UPDATE:-false}
      - OLLAMA_BASE_URL
      - OPENAI_API_KEY
      - GLOBAL_LOG_LEVEL
    networks:
      - external_network
    volumes:
      - data:/app/backend/data
#:media |      - media:$DEPLOY_MEDIA_MOUNT
#:rclone|      - rclone:$DEPLOY_RCLONE_MOUNT
    healthcheck: #!healthcheck
      disable: true #!healthcheck
    deploy:
      replicas: 1
      placement:
        constraints:
          - ${DEPLOY_NODE_WEB:-node.labels.ignore != true}
      labels:
        - "traefik.enable=true" #!no-proxy
        - "traefik.http.routers.${DEPLOY_STACK_NAME:-openwebui}.rule=${DEPLOY_ROUTER_WEB:-Host(\`${DEPLOY_SUBDOMAIN:-openwebui}.${DEPLOY_HOSTNAME}\`)}"
        - "traefik.http.routers.${DEPLOY_STACK_NAME:-openwebui}.entrypoints=webhttps"
#:client-ssl|        - "traefik.http.routers.${DEPLOY_STACK_NAME:-openwebui}.tls.options=sslVerifyClient@file"
        - "traefik.http.routers.${DEPLOY_STACK_NAME:-openwebui}.tls.certresolver=le"
        - "traefik.http.services.${DEPLOY_STACK_NAME:-openwebui}.loadbalancer.server.port=8080"

networks:
  external_network:
    external: true

volumes:
  data:
    driver_opts:
      type: "nfs"
      o: "addr=$DEPLOY_DATA_HOST,${DEPLOY_NFS_OPTS:-nolock,soft,rw}"
      device: ":$DEPLOY_DATA_ROOT/${DEPLOY_STACK_NAME:-openwebui}/data"
#:media |  media:
#:media |    driver_opts:
#:media |      type: "nfs"
#:media |      o: "addr=$DEPLOY_MEDIA_HOST,${DEPLOY_NFS_OPTS:-nolock,soft,rw}"
#:media |      device: ":$DEPLOY_MEDIA_ROOT"
#:rclone|  rclone:
#:rclone|    driver: "rclone"
#:rclone|    driver_opts:
#:rclone|      remote: "$DEPLOY_RCLONE_REMOTE"
