version: "3.8"

x-logging: &loki-logging
    driver: loki
    options:
      loki-url: "${DEPLOY_LOKI_URL}"
      loki-retries: 5
      loki-batch-size: 400

services:
  web:
    image: ${DEPLOY_IMAGE_WEB:-ghcr.io/gethomepage/homepage:v1.5.0}
#:log |    logging: *loki-logging
#:env |    env_file: ${DEPLOY_ENV_WEB}
#:port|    ports:
#:port|      - ${DEPLOY_PORT_WEB:-3000}:3000
    environment:
      #HOMEPAGE_ALLOWED_HOSTS: "${DEPLOY_SUBDOMAIN:-homepage}.${DEPLOY_HOSTNAME}"
      HOMEPAGE_ALLOWED_HOSTS: "*"
      #PUID: 1000
      #PGID: 1000
    networks:
      - external_network
    volumes:
      - data:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    healthcheck: #!healthcheck
      disable: true #!healthcheck
    deploy:
      replicas: 1
      placement:
        constraints: 
          - node.role == manager
          - ${DEPLOY_NODE_WEB:-node.labels.ignore != true}
      labels:
        - "traefik.enable=true" #!no-proxy
        - "traefik.http.routers.${DEPLOY_STACK_NAME:-homepage}.rule=${DEPLOY_ROUTER_WEB:-Host(\`${DEPLOY_SUBDOMAIN:-homepage}.${DEPLOY_HOSTNAME}\`)}"
        - "traefik.http.routers.${DEPLOY_STACK_NAME:-homepage}.entrypoints=webhttps"
#:client-ssl|        - "traefik.http.routers.${DEPLOY_STACK_NAME:-homepage}.tls.options=sslVerifyClient@file"
        - "traefik.http.routers.${DEPLOY_STACK_NAME:-homepage}.tls.certresolver=le"
        - "traefik.http.services.${DEPLOY_STACK_NAME:-homepage}.loadbalancer.server.port=3000"

networks:
  external_network:
    external: true

volumes:
  data:
    driver_opts:
      type: "nfs"
      o: "addr=$DEPLOY_DATA_HOST,nolock,soft,rw"
      device: ":$DEPLOY_DATA_ROOT/${DEPLOY_STACK_NAME:-homepage}/data"
