# see https://docs.searxng.org/admin/settings/settings.html#settings-use-default-settings
use_default_settings: true
server:
  # base_url is defined in the SEARXNG_BASE_URL environment variable, see .env and docker-compose.yml
  secret_key: "my_secretkey"
  limiter: false
  image_proxy: true
ui:
  static_use_hash: true
search:
  formats:
    - html
    - json
redis:
  url: redis://redis:6379/0
